### ISSUE TITLE
redisinsight可以设置公网访问，不需要使用Nginx进行端口转发

### ISSUE THREAD

**Issue by Dawei-Simayi** [websoft9dev/role_redis#14]
在官方文档设置里面，只要将环境变量RIHOST设置相应的公网ip就行了，详情见[configuration](https://docs.redislabs.com/latest/ri/installing/configurations/)

**Comment by chendelin1982** [comment]
Good, 我们将采纳您的建议

**Comment by Dawei-Simayi** [comment]
> Good, 我们将采纳您的建议

您好！我想问一个关于redisInsight的问题，在[文档中](https://docs.redislabs.com/latest/ri/using-redisinsight/memory-analysis/)有一个标题是关于How memory analysis works ，中间有一句话`After the RSNAP file is completely generated, it is uploaded to our servers where further analysis is done to generate recommendations.`，这个应用还会将相应快照的信息上传到他这个公司的服务器上进行分析？还是指在RedisInsight安装机器上进行分析。我觉得的这个servers应该是指存储RSNAP文件的服务器，也就是安装RedisInsight的宿主机。

**Comment by qiaofeng1227** [comment]
redisinsight.config's  REDISINSIGHT_HOST change from 127.0.0.1 to 0.0.0.0
```
[root@iZj6c46ivo1d93ekxma6kvZ ~]# cat /data/config/redisinsight.config 
REDISINSIGHT_PORT=8001
REDISINSIGHT_HOST=0.0.0.0
REDISINSIGHT_HOME_DIR=/usr/local/redisinsight/
LOG_DIR=/var/log/redisinsight/[root@iZj6c46ivo1d93ekxma6kvZ ~]# 

```

**Comment by qiaofeng1227** [comment]
Done
