### ISSUE TITLE
bug：redis.service: Can't open PID file /var/run/redis.pid 

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_redis#2]
运行命令：sudo systemctl status redis
状态是active，但是下面有段报错信息：Can't open PID file /var/run/redis.pid (yet?) after start: No such file or directory
   
Active: active (running) since Mon 2020-02-03 12:33:27 UTC; 1min 9s ago
  Process: 32535 ExecStop=/bin/kill -s QUIT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 32541 ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
 Main PID: 32542 (redis-server)
    Tasks: 3 (limit: 4478)
   CGroup: /system.slice/redis.service
           └─32542 /usr/local/bin/redis-server *:6379

Feb 03 12:33:27 ip-172-31-45-123 systemd[1]: Starting redis...
Feb 03 12:33:27 ip-172-31-45-123 systemd[1]: redis.service: Can't open PID file /var/run/redis.pid (yet?) after start: No such file or directory

**Comment by chendelin1982** [comment]
another error: "ansible_facts.services['redis.service']": "VARIABLE IS NOT DEFINED!"

**Comment by qiaofeng1227** [comment]
Done
