### ISSUE TITLE
 Redis configuration file # bind internet IP cause service can't start

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_redis#7]
Redis configuration file # bind internet IP cause service can't start, it seems only bind local IP

**Comment by qiaofeng1227** [comment]
`127.0.0.1` is a necessary vaule for this item, eg.  
```
# true format
bind 127.0.0.1
bind 127.0.0.1 10.0.0.1

# error format
bind 119.139.121.11

```

**Comment by qiaofeng1227** [comment]
bind is for network interface of Redis Server, when have mutiple network interface, this item may useful.  
comment again,  bind is not for vistor's internet IP

Done
