### ISSUE TITLE
scl enable devtoolset-7 llvm-toolset-7 bash waiting for long time in the task Install GCC for Redis6.0

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_redis#8]
- name: Install GCC for Redis6.0, refer to https://github.com/redis/redis/issues/7509
  shell: |
      sudo yum -y install centos-release-scl devtoolset-7 llvm-toolset-7
      scl enable devtoolset-7 llvm-toolset-7 bash
  when: redis_version == "6.0"

`scl enable devtoolset-7 llvm-toolset-7 bash` seem can't running in Ansible

**Comment by chendelin1982** [comment]
Can you use Ansibel command | raw module to runing `scl enable` ?

**Comment by qiaofeng1227** [comment]
> Can you use Ansibel command | raw module to runing `scl enable` ?

Ansible can running when use command or raw module, but it seems not take effect in current process

**Comment by qiaofeng1227** [comment]
suggest `scl enable` and `make` execute in one command, e.g. `scl enable --make ...`

**Comment by qiaofeng1227** [comment]
Done
